FROM node:latest

# Install ts-node globally
RUN npm install -g ts-node

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Specify the command to run your application
CMD ["ts-node", "src/index.ts"]
 